name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - next
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Bootstrap
        run: npm install
      - name: Check types
        run: npm run lint
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Bootstrap
        run: npm install
      - name: Check build
        run: npm run build
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Bootstrap
        run: npm install
      - name: Run tests
        run: npm test